apiVersion: v1
kind: Service
metadata:
  name: marketing-ai-platform
  namespace: marketing-ai
  labels:
    app: marketing-ai-platform
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: marketing-ai-platform 